

services:

  agent_dashboard:
    build: .
    container_name: agent_dashboard
    restart: unless-stopped
    environment:
      - TZ=America/Asuncion
      - MYSQL_HOST=db_agent
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=agent
    depends_on:
      - db_agent
    networks:
      - platcom_net
    volumes:
      - ./notas:/app/notas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent_dashboard.rule=Host(`${DOMAIN_HOST}`) && PathPrefix(`/agent-journalist`)"
      - "traefik.http.routers.agent_dashboard.entrypoints=web"
      - "traefik.http.services.agent_dashboard.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.agent_dashboard-strip.stripprefix.prefixes=/agent-journalist"
      - "traefik.http.middlewares.agent_dashboard-strip.stripprefix.forceSlash=true"
      - "traefik.http.routers.agent_dashboard.middlewares=agent_dashboard-strip"

  db_agent:
    image: mysql:8.0
    networks:
      - platcom_net
    container_name: db_agent
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: agent
    volumes:
      - dbdata_agent:/var/lib/mysql
    restart: always

networks:
  platcom_net:
    external: true
    name: platcom_net

volumes:
  dbdata_agent:
